package app.lockbook.util

import android.content.Context
import android.net.Uri
import androidx.core.content.edit
import androidx.core.net.toUri
import java.net.URI
import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import java.util.UUID

data class PublicOpenFileRequest(
    val serverOrigin: String,
    val fileId: String,
)

object OpenLinkParser {
    const val OFFICIAL_ORIGIN = "https://app.lockbook.net"
    private val uuidPattern = Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")

    fun parse(value: String): PublicOpenFileRequest? {
        val uri = runCatching { URI(value) }.getOrNull() ?: return null
        if (uri.fragment != null || uri.rawUserInfo != null) return null

        return when (uri.scheme?.lowercase()) {
            "https" -> parseOfficialWebLink(uri)
            "lb" -> parseAppLink(uri)
            else -> null
        }
    }

    fun canonicalOrigin(value: String): String? {
        val uri = runCatching { URI(value) }.getOrNull() ?: return null
        if (
            uri.scheme?.lowercase() != "https" ||
            uri.host == null ||
            uri.rawUserInfo != null ||
            uri.rawQuery != null ||
            uri.fragment != null ||
            (uri.rawPath.isNotEmpty() && uri.rawPath != "/")
        ) {
            return null
        }
        val port = uri.port.takeUnless { it == -1 || it == 443 }
        val host = uri.host.lowercase().let { if (':' in it) "[$it]" else it }
        return buildString {
            append("https://")
            append(host)
            if (port != null) append(":$port")
        }
    }

    fun originsMatch(
        first: String,
        second: String,
    ): Boolean {
        val canonicalFirst = canonicalOrigin(first) ?: return false
        return canonicalFirst == canonicalOrigin(second)
    }

    private fun parseOfficialWebLink(uri: URI): PublicOpenFileRequest? {
        if (uri.rawQuery != null || canonicalOrigin(originOf(uri)) != OFFICIAL_ORIGIN) return null
        val parts = uri.rawPath.split('/').filter(String::isNotEmpty)
        if (parts.size != 2 || parts[0] != "open") return null
        val id = canonicalUuid(parts[1]) ?: return null
        return PublicOpenFileRequest(OFFICIAL_ORIGIN, id)
    }

    private fun parseAppLink(uri: URI): PublicOpenFileRequest? {
        if (uri.rawPath.isNotEmpty() && uri.rawPath != "/") return null
        val authority = uri.host ?: return null

        // Kept for links generated by older Lockbook versions.
        canonicalUuid(authority)?.let { legacyId ->
            if (uri.rawQuery == null) return PublicOpenFileRequest(OFFICIAL_ORIGIN, legacyId)
        }

        if (authority != "open" || uri.rawQuery == null) return null
        val query = parseQuery(uri.rawQuery) ?: return null
        if (query.keys != setOf("server", "file")) return null
        val origin = canonicalOrigin(query.getValue("server")) ?: return null
        val id = canonicalUuid(query.getValue("file")) ?: return null
        return PublicOpenFileRequest(origin, id)
    }

    private fun parseQuery(rawQuery: String): Map<String, String>? {
        val result = mutableMapOf<String, String>()
        for (part in rawQuery.split('&')) {
            val pair = part.split('=', limit = 2)
            if (pair.size != 2) return null
            val key = decode(pair[0]) ?: return null
            val value = decode(pair[1]) ?: return null
            if (result.put(key, value) != null) return null
        }
        return result
    }

    private fun decode(value: String): String? = runCatching { URLDecoder.decode(value, StandardCharsets.UTF_8.name()) }.getOrNull()

    private fun canonicalUuid(value: String): String? {
        if (!uuidPattern.matches(value)) return null
        return runCatching { UUID.fromString(value).toString() }.getOrNull()
    }

    private fun originOf(uri: URI): String = URI(uri.scheme, uri.rawUserInfo, uri.host, uri.port, null, null, null).toString()
}

object OpenLinkBuilder {
    fun build(
        apiUrl: String,
        fileId: String,
    ): String {
        val origin = requireNotNull(OpenLinkParser.canonicalOrigin(apiUrl)) { "Account server must be an HTTPS origin" }
        val id = requireNotNull(OpenLinkParser.parse("lb://$fileId")?.fileId) { "Invalid file id" }
        val originUri = origin.toUri()
        return Uri
            .Builder()
            .scheme("https")
            .encodedAuthority(originUri.encodedAuthority)
            .appendPath("open")
            .appendPath(id)
            .build()
            .toString()
    }
}

object PendingOpenLinkStore {
    private const val PREFERENCES = "pending_open_link"
    private const val SERVER_ORIGIN = "server_origin"
    private const val FILE_ID = "file_id"

    fun save(
        context: Context,
        request: PublicOpenFileRequest,
    ) {
        context
            .getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE)
            .edit {
                putString(SERVER_ORIGIN, request.serverOrigin)
                putString(FILE_ID, request.fileId)
            }
    }

    fun take(context: Context): PublicOpenFileRequest? {
        val preferences = context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE)
        val origin = preferences.getString(SERVER_ORIGIN, null)
        val id = preferences.getString(FILE_ID, null)
        preferences.edit { clear() }
        if (origin == null || id == null) return null
        return OpenLinkParser.parse(
            "lb://open?server=${Uri.encode(origin)}&file=${Uri.encode(id)}",
        )
    }
}
